# Project information
site_name: Markdown Doc Template
site_url: https://yuxiang660.github.io/mkdocs_template/
site_author: Little Bee
site_description: >-
  Create a static site from a set of Markdown files

# Repository
repo_name: yuxiang660/mkdocs_template
repo_url: https://github.com/yuxiang660/mkdocs_template
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 - 2022 Little Bee

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

# Extensions
markdown_extensions:
  # Show contents of a markdown file
  - toc:
      permalink: true
  # Enable "note, tip..." block
  - admonition
  # Enable collapsible function of admonition feature
  - pymdownx.details
  # Block configure
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  # Enable footnote feature
  - footnotes
  # Enable tilde character(~) for delete and subscript
  - pymdownx.tilde
  # Enable caret character(^) for insert and superscript
  - pymdownx.caret
  # Enable LaTeX math equations
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Page tree
nav:
  - Home: index.md
  - Book Notes:
    - markdown/README.md
    - mkdocs_enhance/README.md
